# Commented conf lines are the default values

# listen_adress = "0.0.0.0:8000"

[outbound_proxy]
# listen_adress = "0.0.0.0:3128"

ca_priv_key_path = "ca.pem"
ca_cert_path = "ca.crt"

[outbound_proxy.upstream_proxy]
url = "https://127.0.0.1:3128"
ca_pem = "==BEGIN CERTIFICATE==\n...\n==END CERTIFICATE=="

allowed_non_matrix_regexes_dangerous = [
    "https://ntfy\\.sh/.*"
]

[[internal_homeservers]]
server_name = "tout.im"
federation_domain = "matrix.tout.im"
destination_base_url = "http://localhost:8008"

[[external_homeservers]]
server_name = "matrix.org"
federation_domain = "matrix-federation.matrix.org:443"
client_domain = "matrix-client.matrix.org:443"
verify_keys = { "ed25519:a_RXGa" = "l8Hft5qXKn1vfHrg3p4+W8gELQVo8N13JkluMfmn2sQ" }
